title: drum-star
hero_image: images/banner.png
description: drum-star description
version: 4
listed: false
copyedit: false
last_tested: "2021-04-28"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
