title: explore-project-template
hero_image: images/banner.png
description: explore-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Set the Stage
  - title: First drum
  - title: First upgrade
  - title: Second upgrade
  - title: Add another drum
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
