---
title: ड्रम स्टार
hero_image: images/banner.png
description: एक क्लिकर गेम बनाएं जहां आप नए ड्रम और बड़े स्थानों को बजाने के लिए बीट्स अर्जित करेंगे
version: 4
listed: false
copyedit: false
last_tested: "2021-04-28"
steps:
  - 
    title: परिचय
  - 
    title: मंच तैयार करें
  - 
    title: स्टार्टर ड्रम
    completion: engaged
  - 
    title: पहला अपग्रेड
  - 
    title: दूसरा अपग्रेड
  - 
    title: खेलें और अपनी रुचि के अनुसार बनाएँ
    completion: internal
  - 
    title: सोचिए
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: प्रोजेक्ट को अपग्रेड करें
  - 
    title: आगे क्या?
