---
title: డ్రమ్ స్టార్
hero_image: images/banner.png
description: ఈ ప్రాజెక్ట్‌లో, మీరు పెద్ద వేదికల వద్ద డ్రమ్స్ వాయించేందుకు కొత్త బీట్‌లను సంపాదించే క్లిక్కర్ గేమ్‌ను తయారు చేస్తారు
version: 4
listed: true
copyedit: true
last_tested: "2021-04-28"
steps:
  - 
    title: You will make
  - 
    title: Stage ను సెట్ చేయండి
  - 
    title: స్టార్టర్ డ్రమ్
    completion:
      - engaged
  - 
    title: మొదటి అప్‌గ్రేడ్
  - 
    title: రెండవ అప్‌గ్రేడ్
  - 
    title: ప్లే చేయండి మరియు కస్టమైజ్ చేయండి
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: మీ ప్రాజెక్ట్‌ను అప్‌గ్రేడ్ చేయండి
  - 
    title: తర్వాత ఏంటి?
