---
title: Estrela do tambor
hero_image: images/banner.png
description: Neste projeto, você fará um jogo clicker onde ganhará batidas para tocar bateria nova em locais maiores
meta_title: Projetos de codificação Scratch para crianças e adolescentes | Estrela do tambor
meta_description: Aprenda Scratch com os projetos de codificação da Raspberry Pi Foundation para crianças e adolescentes. Faça um jogo Scratch onde você ganha batidas para tocar novas baterias em locais maiores.
version: 4
listed: true
copyedit: true
last_tested: "2021-04-28"
steps:
  - 
    title: Você fará
  - 
    title: Prepare o cenário
  - 
    title: Tambor inicial
    completion:
      - engaged
  - 
    title: Primeira atualização
  - 
    title: Segunda atualização
  - 
    title: Jogue e personalize
    completion:
      - internal
  - 
    title: Perguntas rápidas
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Melhore o seu projeto
  - 
    title: E agora?
