---
title: Estrela do tambor
hero_image: images/banner.png
description: Neste projeto, você fará um jogo clicker onde ganhará batidas para tocar bateria nova em locais maiores
pdf: resources/rpfi-drum-stars.pdf
meta_title: Projetos de codificação Scratch para crianças e adolescentes | Estrela do tambor
meta_description: Aprenda Scratch com os projetos de codificação da Raspberry Pi Foundation para crianças e adolescentes. Faça um jogo Scratch onde você ganha batidas para tocar novas baterias em locais maiores.
version: 4
listed: true
copyedit: true
last_tested: "2021-04-28"
steps:
  - 
    title: What you will make
  - 
    title: Prepare o cenário
  - 
    title: Tambor inicial
    completion:
      - engaged
  - 
    title: Next drum
  - 
    title: More drums!
  - 
    title: Play
    completion:
      - internal
  - 
    title: Perguntas rápidas
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
