---
title: Estrella de los tambores
hero_image: images/banner.png
description: Crea un juego de clics en donde ganas ritmos para tocar nuevos tambores y en lugares más grandes
meta_title: Scratch coding projects for kids and teens | Drum star
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch game where you earn beats to play new drums at bigger venues.
version: 4
listed: true
copyedit: true
last_tested: "2021-04-28"
steps:
  - 
    title: What you will make
  - 
    title: Prepara el escenario
  - 
    title: Tambor de principiante
    completion:
      - engaged
  - 
    title: Next drum
  - 
    title: More drums!
  - 
    title: Play
    completion:
      - internal
  - 
    title: Examen rápido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Challenge
    challenge: true
  - 
    title: '¿Qué sigue?'
