---
title: نجم الطبل
hero_image: images/banner.png
description: في هذا المشروع، سوف تصنع لعبة نقر حيث تربح إيقاعات لعزف طبول جديدة في أماكن أكبر
pdf: resources/rpfi-drum-stars.pdf
meta_title: Scratch coding projects for kids and teens | Drum star
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch game where you earn beats to play new drums at bigger venues.
version: 4
listed: true
copyedit: true
last_tested: "2021-04-28"
steps:
  - 
    title: What you will make
  - 
    title: جهز المسرح
  - 
    title: بداية مرحلة الطبل
    completion:
      - مرتبط
  - 
    title: Next drum
  - 
    title: More drums!
  - 
    title: Play
    completion:
      - داخلي
  - 
    title: اختبار سريع
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - خارجي
  - 
    title: Challenge
    challenge: true
