---
title: نجم الطبل
hero_image: images/banner.png
description: في هذا المشروع، سوف تصنع لعبة نقر حيث تربح إيقاعات لعزف طبول جديدة في أماكن أكبر
version: 4
listed: true
copyedit: true
last_tested: "2021-04-28"
steps:
  - 
    title: سوف تصنع
  - 
    title: جهز المسرح
  - 
    title: بداية مرحلة الطبل
    completion:
      - مرتبط
  - 
    title: التطوير الأول للمشروع
  - 
    title: التطوير الثاني للمشروع
  - 
    title: مرحلة العب وخصص
    completion:
      - داخلي
  - 
    title: اختبار سريع
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - خارجي
  - 
    title: قم بترقية مشروعك
  - 
    title: ما التالي؟
