---
title: Drum star
hero_image: images/banner.png
description: Make a clicker game where you earn beats to play new drums and bigger venues
version: 4
listed: true
copyedit: true
last_tested: "2021-04-28"
steps:
  - 
    title: Εισαγωγή
  - 
    title: Επίλεξε το Σκηνικό
  - 
    title: Starter drum
    completion: engaged
  - 
    title: Πρώτη αναβάθμιση
  - 
    title: Δεύτερη αναβάθμιση
  - 
    title: Παίξε και προσάρμοσε
    completion: internal
  - 
    title: Αναστοχασμός
    completion: external
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - 
    title: Αναβάθμισε το έργο σου
  - 
    title: Και τώρα;
