---
title: Star du tambour
hero_image: images/banner.png
description: Créer un jeu de clics où tu gagnes des battements pour jouer de nouveaux tambours et dans de plus grandes salles
meta_title: Scratch coding projects for kids and teens | Drum star
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch game where you earn beats to play new drums at bigger venues.
version: 4
listed: true
copyedit: true
last_tested: "2021-04-28"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Mise en place de la scène
  - 
    title: Tambour de départ
    completion:
      - engaged
  - 
    title: Première amélioration
  - 
    title: Deuxième amélioration
  - 
    title: Jouer et personnaliser
    completion:
      - internal
  - 
    title: Questionnaire rapide
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Améliorer ton projet
  - 
    title: Et ensuite ?
