---
title: Drum star
hero_image: images/banner.png
description: Make a clicker game where you earn beats to play new drums and bigger venues
meta_title: Scratch coding projects for kids and teens | Drum star
meta_description: Learn Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch game where you earn beats to play new drums at bigger venues.
version: 4
listed: true
copyedit: true
last_tested: "2021-04-28"
steps:
  - 
    title: You will make
  - 
    title: Set the Stage
  - 
    title: Starter drum
    completion:
      - engaged
  - 
    title: First upgrade
  - 
    title: Second upgrade
  - 
    title: Play and customise
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Upgrade your project
  - 
    title: What next?
